accounts/urls.py
from django.urls import path
from accounts import views

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

delivery_app/urls.py
from django.urls import path
from delivery_app import views

urlpatterns = [
    path('', views.AllDeliveriesView.as_view(), name='index'),
    path('clients-info/', views.ClientsInfoView.as_view(), name='clients-info'),
    path('create-client/', views.CreateClientView.as_view(), name='create-client'),
    path('order/create', views.CreateOrderView.as_view(), name='create-order'),
    path('order/create-datetime/', views.CreateOrderDateTimeView.as_view(), name='create-order-datetime'),
    path('order/<int:order_number>/', views.OrderDetailView.as_view(), name='order-info'),
    path('deliveries/all', views.AllDeliveriesView.as_view(), name='all-deliveries')
]

django_delivery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('delivery_app.urls')),
    path('', include('accounts.urls'))
]

delivery_app/models.py
from django.db import models
from django.conf import settings


class Client(models.Model):
    name = models.CharField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=20, unique=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['orders__created_at']


class DeliveryAddress(models.Model):
    city = models.CharField(max_length=50)
    street = models.CharField(max_length=50)
    house = models.IntegerField()
    apartment = models.IntegerField(blank=True, null=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='addresses')

    class Meta:
        verbose_name_plural = 'Delivery addresses'

    def __str__(self):
        return f'City: {self.city}, street: {self.street}'


class Driver(models.Model):
    name = models.CharField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=20, unique=True)
    vehicle_code = models.IntegerField(unique=True)
    vehicle_name = models.CharField(max_length=50)
    vehicle_max_weight = models.IntegerField()
    vehicle_max_volume = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} {self.vehicle_name}'


class OrderInfo(models.Model):

    STATUS_CHOICES = [
        ('confirmed', 'Підтверджено'),
        ('on_the_way', 'В дорозі'),
        ('delivered', 'Доставлено'),
        ('canceled', 'Відмінено')
    ]
    ADRESS_CHOICES = [
        ('address1', "Склад №1"),
        ('address2', "Склад №2")
    ]

    order_number = models.IntegerField(unique=True)
    order_weight = models.IntegerField()
    order_volume = models.DecimalField(max_digits=10, decimal_places=2)
    order_amount = models.DecimalField(max_digits=10, decimal_places=2)
    delivery_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    distance = models.IntegerField()
    order_adress = models.CharField(max_length=50, choices=ADRESS_CHOICES)
    unload_service = models.BooleanField(default=False)
    manipulator_service = models.BooleanField(default=False)
    additional_info = models.TextField(blank=True, null=True)
    ship_date = models.DateField(blank=True, null=True)
    ship_time = models.TimeField(blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='confirmed')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField()
    client = models.ForeignKey(Client, on_delete=models.PROTECT, related_name='orders')
    address = models.ForeignKey(DeliveryAddress, on_delete=models.CASCADE, related_name='order')
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='manager')
    driver = models.ForeignKey(Driver, on_delete=models.PROTECT, blank=True, null=True, related_name='driver')

    class Meta:
        verbose_name_plural = 'Orders info'

    def __str__(self):
        return f'{self.order_number} {self.client.name}'

delivery_app/forms.py
from django import forms
from delivery_app.models import Client, DeliveryAddress, OrderInfo


class CreateClientForm(forms.ModelForm):
    title = 'Дані про клієнта'

    class Meta:
        model = Client
        fields = ['name', 'phone_number']
        labels = {
            'name': "Імʼя",
            'phone_number': 'Номер телефону'
        }


class CreateDeliveryAddressForm(forms.ModelForm):
    title = 'Адреса клієнта'

    class Meta:
        model = DeliveryAddress
        fields = ['city', 'street', 'house', 'apartment']
        labels = {
            'city': "Населений пункт",
            'street': 'Вулиця',
            'house': 'Будинок',
            'apartment': 'Квартира',
        }


class CreateOrderForm(forms.ModelForm):
    title = 'Дані доставки'

    class Meta:
        model = OrderInfo
        fields = [
            'order_number',
            'order_weight',
            'order_volume',
            'order_amount',
            'order_adress',
            'distance',
            'unload_service',
            'manipulator_service',
            'additional_info'
        ]
        labels = {
            'order_number': "Номер замовлення",
            'order_weight': 'Вага замовлення',
            'order_volume': "Обʼєм замовлення",
            'order_amount': 'Сума замовлення',
            'order_adress': "Склад відвантаження",
            'distance': 'Кілометраж',
            'unload_service': 'Розвантаження замовлення',
            'manipulator_service': 'Послуги маніпулятора',
            'additional_info': 'Додаткова інформація',
        }


class CreateOrderDateTimeForm(forms.ModelForm):
    title = 'Дата та час доставки'

    class Meta:
        model = OrderInfo
        fields = ['ship_date', 'ship_time']
        labels = {
            'ship_date': 'Дата доставки',
            'ship_time': 'Час доставки',
        }


class OrderFilterForm(forms.Form):
    client = forms.CharField(max_length=100, required=False, label='Клієнт')
    order = forms.IntegerField(required=False, label='Номер замовлення')

delivery_app/views.py
from datetime import datetime

from django.forms import BaseModelForm
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.views import View
from django.views.generic import CreateView, ListView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.core.exceptions import ValidationError, ObjectDoesNotExist

from delivery_app import models
from delivery_app import forms


def index(request):
    context = {
        'render_string': 'Hello, world!'
    }
    return render(request, template_name='delivery_app/index.html', context=context)


class CreateClientView(LoginRequiredMixin, CreateView):
    title = "Створення клієнта"
    model = models.Client
    template_name = 'delivery_app/client_form.html'
    form_class = forms.CreateClientForm
    success_url = reverse_lazy('clients-info')

    def form_invalid(self, form):
        client_name = self.request.POST.get('name')
        phone_number = self.request.POST.get('phone_number')
        try:
            client = models.Client.objects.get(name=client_name)
            if client:
                form = forms.CreateClientForm(instance=client)
                return render(self.request, self.template_name, {'form': form})
        except ObjectDoesNotExist:
            client = models.Client.objects.get(phone_number=phone_number)
            if client:
                form = forms.CreateClientForm(instance=client)
                return render(self.request, self.template_name, {'form': form})


class ClientsInfoView(LoginRequiredMixin, ListView):
    model = models.Client
    context_object_name = 'clients'
    template_name = 'delivery_app/clients_info.html'


class CreateOrderView(LoginRequiredMixin, CreateView):
    template_name = 'delivery_app/create_order_form.html'
    success_url = reverse_lazy('create-order-datetime')

    def get_context_data(self, **kwargs):
        client_form = forms.CreateClientForm()
        address_form = forms.CreateDeliveryAddressForm()
        order_form = forms.CreateOrderForm()
        context = {
            'form1': client_form,
            'form2': address_form,
            'form3': order_form
        }
        return context

    def get(self, request, *args, **kwargs):
        if 'order_id' in request.session:
            del self.request.session['order_id']
        context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        client_form = forms.CreateClientForm(request.POST)
        address_form = forms.CreateDeliveryAddressForm(request.POST)
        order_form = forms.CreateOrderForm(request.POST)
        if client_form.is_valid():
            client = client_form.save(commit=False)
        else:
            client_name = client_form.data['name']
            try:
                client = models.Client.objects.get(name=client_name)  # витягти клієнта з бази
            except (IntegrityError, ObjectDoesNotExist) as e:
                client_form.add_error('name', e)
                return render(request, self.template_name, {'form1': client_form})
        if address_form.is_valid():
            address = address_form.save(commit=False)
            address.client = client
            client.save()
        else:
            # address_form.add_error('Щось пішло не так!')
            return render(request, self.template_name, {'form2': address_form})
        if order_form.is_valid():
            order = order_form.save(commit=False)
            order.client = client
            order.manager = request.user
            order.updated_at = datetime.now()
            order.address = address
            address.save()
            order.save()
        else:
            order_form.add_error(None, 'Щось пішло не так!')
            return render(request, self.template_name, {'form3': order_form})
        request.session['order_id'] = order.id
        return redirect(reverse_lazy('create-order-datetime'))


class CreateOrderDateTimeView(LoginRequiredMixin, CreateView):
    template_name = 'delivery_app/create_order_datetime_form.html'
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        order_id = self.request.session.get('order_id')
        order = models.OrderInfo.objects.get(id=order_id)
        order_manager = order.manager
        order_driver = self.get_driver(order)
        order.delivery_amount = self.get_delivery_price(order)
        order.save()
        self.request.session['order_driver_id'] = order_driver.id
        datetime_form = forms.CreateOrderDateTimeForm()
        context = {
            'order_manager': order_manager,
            'datetime_form': datetime_form,
            'order_driver': order_driver,
            'delivery_amount': order.delivery_amount
        }
        return context

    def get(self, request, *args, **kwargs):
        if 'order_id' in self.request.session:
            context = self.get_context_data(**kwargs)
            return render(request, self.template_name, context)
        else:
            return redirect('create-order')

    def post(self, request, *args, **kwargs):
        datetime_form = forms.CreateOrderDateTimeForm(request.POST)
        if datetime_form.is_valid():
            order_id = request.session.get('order_id')
            order_driver_id = request.session.get('order_driver_id')
            order_driver = models.Driver.objects.get(id=order_driver_id)
            order = models.OrderInfo.objects.get(id=order_id)
            order.ship_date = datetime_form.cleaned_data['ship_date']
            order.ship_time = datetime_form.cleaned_data['ship_time']
            order.driver = order_driver
            order.save()
        else:
            # raise ValidationError(datetime_form.errors)
            return render(request, self.template_name, self.context)
        return redirect('order-info', order_number=order.id)

    def get_driver(self, order):
        order_volume = order.order_volume
        order_weight = order.order_weight
        driver = models.Driver.objects.filter(vehicle_max_weight__lt=order_weight, vehicle_max_volume__lt=order_volume)
        if driver:
            return driver[0]
        else:
            driver = models.Driver.objects.get(id=1)
            return driver

    def get_delivery_price(self, order):
        price = 0
        if order.order_weight < 2000:
            price = order.distance * 30
        if 2000 <= order.order_weight < 3000:
            price = order.distance * 40
        if order.order_weight >= 3000:
            price = order.distance * 50
        if order.unload_service and order.manipulator_service:
            price *= 2.5
        elif order.unload_service:
            price *= 2
        elif order.manipulator_service:
            price *= 1.5

        return price


class OrderDetailView(LoginRequiredMixin, DetailView):
    template_name = 'delivery_app/order_detail.html'
    model = models.OrderInfo
    context_object_name = 'order'
    pk_url_kwarg = 'order_number'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'order_id' in self.request.session:
            del self.request.session['order_id']
        if 'driver_id' in self.request.session:
            del self.request.session['driver_id']
        return context


class AllDeliveriesView(LoginRequiredMixin, ListView):
    template_name = 'delivery_app/all_deliveries.html'
    model = models.OrderInfo
    context_object_name = 'orders'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.OrderFilterForm(self.request.GET)
        return context

    def get_queryset(self):
        query_set = super().get_queryset()
        client = self.request.GET.get('client', '')
        order_number = self.request.GET.get('order', '')
        if order_number:
            query_set = query_set.filter(order_number=order_number)
        if client:
            query_set = query_set.filter(client__name=client)
        return query_set.order_by('ship_date')

templates/delivery_app/all_deliveries.html
{% extends 'base.html' %}
{% block content %}
<!--<form class="all_deliver" method="post">-->

<form method="GET">
    {% csrf_token %}
    {{ form.client.label_tag }}
    {{ form.client }}
    {{ form.order.label_tag }}
    {{ form.order }}
    <input id="submit" type="submit" value="Фільтрувати"></input>
</form>
<div class="all_deliver">
    <table>
        <thead>
            <tr>
                <th>Дата доставки</th>
                <th>Код доставки</th>
                <th>ПІБ водія</th>
                <th>Код транспорту</th>
                <th>ПІБ менеджера</th>
                <th>Клієнт</th>
                <th>Вартість доставки</th>
                <th>Статус доставки</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{ order.ship_date|date:"d.m.Y" }}</td>
                <td><a href="{% url 'order-info' order.pk %}">{{ order.order_number }}</a></td>
                <td>{{ order.driver.name }}</td>
                <td>{{ order.driver.vehicle_code }}</td>
                <td>{{ order.manager.first_name }}</td>
                <td>{{ order.client.name }}</td>
                <td>{{ order.delivery_amount }}</td>
                <td>{{ order.get_status_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<!--</form>-->
{% endblock %}

templates/delivery_app/client_form.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    <fieldset>
        <h2>Створення клієнта</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зберегти</button>
    </fieldset>
</form>
{% endblock %}

templates/delivery_app/clients_info.html
{% extends 'base.html' %}
{% block content %}
    {% for client in clients %}
        <h1>Client name: {{ client.name }}</h1>
        <h2>Client phone number: {{ client.phone_number }}</h2>
    {% endfor %}
{% endblock %}

templates/delivery_app/create_order.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h2>{{ view.title }}</h2>
    <form method="post">
        {% csrf_token %}
        <h2>{{ form1.title }}</h2>
        {{ form1.as_p }}
        <h2>{{ form2.title }}</h2>
        {{ form2.as_p }}
        <h2>{{ form3.title }}</h2>
        {{ form3.as_p }}
        <button type="submit">Оформити доставку</button>
    </form>
</div>
{% endblock %}

templates/delivery_app/create_order_datetime.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    <fieldset>
        <h2>{{ form.title }}</h2>
        <h2>Менеджер</h2>
        <p>{{ order_manager.first_name }} {{ order_manager.last_name }}</p>
        <p>{{ order_manager.phone_number }}</p>
        <h2>Дата та час доставки</h2>
        {% csrf_token %}
        {{ datetime_form.as_p }}
        <h2>Підбір транспорту</h2>
        <p>{{ order_driver.vehicle_code }} | {{ order_driver.vehicle_name }}</p>
        <p>{{ order_driver.vehicle_max_volume }} | {{ order_driver.vehicle_max_weight }}</p>
        <p>ВАРТІСТЬ ДОСТАВКИ: 4500 грн</p>
        <button type="submit">Підтвердити доставку</button>
    </fieldset>
</form>
{% endblock %}

templates/delivery_app/create_order_datetime_form.html
{% extends 'base.html' %}
{% block content %}
<form class="my_form" method="post">
    {% csrf_token %}
    <fieldset>
        <h2>Менеджер оформлюваної доставки</h2>
        <label>ПІБ:
            <input class="big" type="text" value="{{ order_manager.first_name }} {{ order_manager.last_name }}" disabled />
        </label>
        <label>Номер телефону:
            <input class="big" type="tel" value="{{ order_manager.phone_number }}" disabled />
        </label>
    </fieldset>
    <fieldset>
        <h2>Дата та час доставки</h2>
        <label for="{{ datetime_form.ship_date.id_for_label }}">Дата доставки:
            <input  id="{{ datetime_form.ship_date.id_for_label }}" name="{{ datetime_form.ship_date.html_name }}"
                    type="date" placeholder="Оберіть дату" required />
        </label>
        <label for="{{ datetime_form.ship_time.id_for_label }}">Час доставки:
            <input  id="{{ datetime_form.ship_time.id_for_label }}" name="{{ datetime_form.ship_time.html_name }}"
                    type="time" placeholder="Оберіть час" required />
        </label>
    </fieldset>
    <fieldset class>
        <h2>Підбір транспорту</h2>
        <div class="big">
            <section class="section_text">
                <p>Код транспортного засобу</p>
                <p class="role">{{ order_driver.vehicle_code }}</p>
            </section>
            <section class="section_text">
                <p>Назва транспортного засобу</p>
                <p class="role">{{ order_driver.vehicle_name }}</p>
            </section>
            <section class="section_text">
                <p>Макс. дозволений об'єм (м/кб)</p>
                <p class="role">{{ order_driver.vehicle_max_volume }}</p>
            </section>
            <section class="section_text">
                <p>Макс. дозволена вага (т)</p>
                <p class="role">{{ order_driver.vehicle_max_weight }}</p>
            </section>
        </div>
    </fieldset>
    <section>
        <h2 class="uppercase">Вартість доставки:</h2>
        <section>
            <h2 class="small">{{ delivery_amount }}</h2>
            <h2 class="small"> грн</h2>
        </section>
    </section>
    <input id="submit" type="submit" value="Підтвердити доставку"/>
</form>
{% endblock %}
<!--<form method="post">-->
<!--    <fieldset>-->
<!--        {% csrf_token %}-->
<!--        <h2>{{ form.title }}</h2>-->
<!--        <h2>Менеджер</h2>-->
<!--        <p>{{ order_manager.first_name }} {{ order_manager.last_name }}</p>-->
<!--        <p>{{ order_manager.phone_number }}</p>-->
<!--        <h2>Дата та час доставки</h2>-->
<!--        {{ datetime_form.as_p }}-->
<!--        <h2>Підбір транспорту</h2>-->
<!--        <p>{{ order_driver.vehicle_code }} | {{ order_driver.vehicle_name }}</p>-->
<!--        <p>{{ order_driver.vehicle_max_volume }} | {{ order_driver.vehicle_max_weight }}</p>-->
<!--        <p>ВАРТІСТЬ ДОСТАВКИ: {{ delivery_amount }} грн</p>-->
<!--        <button type="submit">Підтвердити доставку</button>-->
<!--    </fieldset>-->
<!--</form>-->

templates/delivery_app/index.html
{% extends 'base.html' %}
{% block content %}
    {% if request.user.is_authenticated %}
        <h1>Hello, you are aunthentificated!</h1>
    {% else %}
        <h1>Hello, you are unaunthentificated!</h1>
    {% endif %}
    <a href="{% url 'clients-info' %}">Go to clients info</a>
    <br>
    <a href="{% url 'create-client' %}">Go to create client</a>
    <br>
    <a href="{% url 'register' %}">Go to create user</a>
{% endblock %}

templates/delivery_app/login.html
{% extends 'base.html' %}
{% block content %}
<form id="login" method="post">
    {% csrf_token %}
    <h2 class="uppercase">Вхід</h2>
    <fieldset class = "login">
        <input class="big" id="log" name="{{ form.username.html_name }}" type="text" placeholder="Логін:" autofocus autocomplete="username"
               required />
        <input class="big" id="pas" name="{{ form.password.html_name }}" type="password" placeholder="Пароль:"
               autocomplete="current-password"
               required />
    </fieldset>
    <input id="submit" type="submit" value="Вхід"/>
</form>
<!--<button onclick='window.location.href="{% url "register" %}"'>Реєстрація</button>-->
{% endblock %}

templates/delivery_app/order_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="detail">
    <div class="center">
    <h2 class="uppercase">Доставка</h2>
    <section class="marg">
        <p class="about_text">Дата:</p>
        <section class="some">
            <p class="small">{{ order.ship_date|date:"d.m.Y" }}</p>
        </section>
        <p class="about_text">Час:</p>
        <section>
            <p class="small">{{ order.ship_time|time:"H:i"}}</p>
        </section>
    </section>
    </div>
    <fieldset >
        <h2>Менеджер</h2>
        <section >
            <p class="about_text">ПІБ:</p>
            <section>
                <p class="small">{{ order.manager.first_name }} {{ order.manager.last_name }}</p>
            </section>
        </section>
        <section >
            <p class="about_text">Номер телефону:</p>
            <section>
                <p class="small">+{{ order.manager.phone_number }}</p>
            </section>
        </section>
    </fieldset>
    <fieldset >
        <h2>Водій</h2>
        <section >
            <p class="about_text">ПІБ:</p>
            <section>
                <p class="small">{{ order.driver.name }}</p>
            </section>
        </section>
        <section >
            <p class="about_text">Номер телефону:</p>
            <section>
                <p class="small">+{{ order.driver.phone_number }}</p>
            </section>
        </section>
        <section >
            <p class="about_text">Код транспортного засобу:</p>
            <section>
                <p class="small">{{ order.driver.vehicle_code }}</p>
            </section>
        </section>
        <section >
            <p class="about_text">Назва транспортного засобу:</p>
            <section>
                <p class="small">{{ order.driver.vehicle_name }}</p>
            </section>
        </section>
        <section >
            <p class="about_text">Maкс. допустима вага вантажу:</p>
            <section>
                <p class="small">{{ order.driver.vehicle_max_weight }}</p>
                <p class="small">кг</p>
            </section>
        </section>
        <section >
            <p class="about_text">Maкс. допустимий об’єм вантажу:</p>
            <section>
                <p class="small">{{ order.driver.vehicle_max_volume }}</p>
                <p class="small">м/куб</p>
            </section>
        </section>
    </fieldset>
    <fieldset >
        <h2>Клієнт</h2>
        <section >
            <p class="about_text">ПІБ / Назва компанії:</p>
            <section>
                <p class="small">{{ order.client.name }}</p>
            </section>
        </section>
        <section >
            <p class="about_text">Номер телефону:</p>
            <section>
                <p class="small">+{{ order.client.phone_number }}</p>
            </section>
        </section>
    </fieldset>
    <fieldset >
        <h2>Адреса доставки</h2>
        <section >
            <p class="about_text">Населений пункт:</p>
            <section>
                <p class="small">{{ order.address.city }}</p>
            </section>
        </section>
        <section >
            <p class="about_text">Вулиця:</p>
            <section>
                <p class="small">{{ order.address.street }}</p>
            </section>
        </section>
        <section >
            <p class="about_text">Будинок:</p>
            <section>
                <p class="small">{{ order.address.house }}</p>
            </section>
        </section>
        <section >
            <p class="about_text">Квартира:</p>
            <section>
                <p class="small">{{ order.address.appartment }}</p>
            </section>
        </section>
    </fieldset>
    <fieldset>
        <h2>Дані доставки</h2>
        <section >
            <p class="about_text">Номер замовлення:</p>
            <section>
                <p class="small">{{ order.order_number }}</p>
            </section>
        </section>
        <section >
            <p class="about_text">Вага замовлення:</p>
            <section>
                <p class="small">{{ order.order_weight }}</p>
                <p class="small">кг</p>
            </section>
        </section>
        <section >
            <p class="about_text">Об'єм замвлення:</p>
            <section>
                <p class="small">{{ order.order_volume }}</p>
                <p class="small">м/куб</p>
            </section>
        </section>
        <section >
            <p class="about_text">Сума замовлення:</p>
            <section>
                <p class="small">{{ order.order_amount }}</p>
                <p class="small">грн</p>
            </section>
        </section>
        <section >
            <p class="about_text">Вартість доставки:</p>
            <section>
                <p class="small">{{ order.delivery_amount }}</p>
                <p class="small">грн</p>
            </section>
        </section>
        <section >
            <p class="about_text">Склад відвантаження:</p>
            <section>
                <p class="small">{{ order.get_order_adress_display }}</p>
            </section>
        </section>
        <section >
            <p class="about_text">Додаткові послуги:</p>
            <section>
                {% if order.unload_service %}
                <p class="small">Розвантаження замовлення</p>
                {% endif %}
                {% if order.manipulator_service %}
                <p class="small">Послуги маніпулятора</p>
                {% endif %}
            </section>
        </section>
        <section >
            <p class="about_text">Додаткова інформація:</p>
            <section>
                <p class="small">{{ order.additional_info }}</p>
            </section>
        </section>
    </fieldset>
    <input onclick='window.location.href="{% url "index" %}"' id="submit" type="submit" value="Підтвердити"/>
</div>
{% endblock %}

templates/delivery_app/register.html
{% extends 'base.html' %}
{% block content %}
<fieldset>
    <form method="post">
        <h2>Registration</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</fieldset>
{% endblock %}